2017-05-09T20:44:02.6919809-07:00  [INF] >referencetablevalue generated and set in cache. (23a800fd)
2017-05-09T20:44:03.5763329-07:00  [INF] Saved 4 entities to in-memory store. (3b5ca34b)
2017-05-09T20:44:03.9107218-07:00  [INF] User profile is available. Using '"C:\Users\jimmy\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest. (7ac5e29c)
2017-05-09T20:44:06.6915092-07:00 0HL4NAR7KOUQD [INF] Request starting HTTP/1.1 GET http://localhost:52437/   (e5be5b71)
2017-05-09T20:44:07.3046384-07:00 0HL4NAR7KOUQD [INF] Request finished in 653.4401ms 404  (15c52c40)
2017-05-09T20:44:11.3553944-07:00 0HL4NAR7KOUQE [INF] Request starting HTTP/1.1 GET http://localhost:52437/claim   (e5be5b71)
2017-05-09T20:44:11.6154887-07:00 0HL4NAR7KOUQE [INF] Executing action method "DIA.Web.Controllers.ClaimController.Index (DIA.Web)" with arguments (["", "", ""]) - ModelState is Valid (ba7f4ac2)
2017-05-09T20:44:12.0297688-07:00 0HL4NAR7KOUQE [INF] Executed action "DIA.Web.Controllers.ClaimController.Index (DIA.Web)" in 541.7878ms (afa2e885)
2017-05-09T20:44:12.1137775-07:00 0HL4NAR7KOUQE [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IEntityQueryProvider can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at PaginatedList`1.<CreateAsync>d__13.MoveNext() in C:\Users\jimmy\Documents\Visual Studio 2017\Projects\DIA\DIA.Web\PaginatedList.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DIA.Web.Controllers.ClaimController.<Index>d__5.MoveNext() in C:\Users\jimmy\Documents\Visual Studio 2017\Projects\DIA\DIA.Web\Controllers\ClaimController.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-05-09T20:44:12.4115698-07:00 0HL4NAR7KOUQE [INF] Request finished in 1051.8988ms 500 text/html; charset=utf-8 (15c52c40)
